# Generated by Django 3.1.7 on 2021-03-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_movie_id', models.CharField(max_length=250)),
                ('Title', models.CharField(max_length=250)),
                ('Released', models.CharField(max_length=250)),
                ('Runtime', models.CharField(max_length=250)),
                ('Genre', models.CharField(max_length=250)),
                ('Director', models.CharField(max_length=250)),
                ('Writer', models.CharField(max_length=250)),
                ('story_line', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Awards', models.CharField(max_length=250)),
                ('Poster', models.CharField(max_length=250)),
            ],
        ),
    ]
